repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.1.0
    hooks:
    -   id: eslint
        files: client/js/
        args: ['--fix']
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.2'
    hooks:
    -   id: flake8
        files: server/szurubooru/
        additional_dependencies:
          -   flake8-print
        args: ['--config=server/setup.cfg']
exclude: LICENSE.md
